name: Build Push Deploy Lambda

on:
  push:
    branches:
      - test
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    # THIS LINE LOADS ENVIRONMENT SECRETS
    environment: ${{ github.ref_name == 'main' && 'production' || 'test' }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect Environment
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY_PROD }}" >> $GITHUB_ENV
            echo "LAMBDA_NAME=${{ secrets.LAMBDA_FUNCTION_NAME_PROD }}" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=test" >> $GITHUB_ENV
            echo "ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY_TEST }}" >> $GITHUB_ENV
            echo "LAMBDA_NAME=${{ secrets.LAMBDA_FUNCTION_NAME_TEST }}" >> $GITHUB_ENV
          fi

      - name: Set Image URI
        run: |
          echo "IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY" >> $GITHUB_ENV

      - name: Debug Variables
        run: |
          echo "Branch: ${GITHUB_REF##*/}"
          echo "Environment: $ENVIRONMENT"
          echo "Repository: $ECR_REPOSITORY"
          echo "Lambda: $LAMBDA_NAME"
          echo "Image URI: $IMAGE_URI"
          echo "Region: ${{ secrets.AWS_REGION }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build --platform linux/amd64 \
          -t $IMAGE_URI:$IMAGE_TAG \
          -t $IMAGE_URI:latest .

      - name: Push Images to ECR
        run: |
          docker push $IMAGE_URI:$IMAGE_TAG
          docker push $IMAGE_URI:latest

      - name: Wait for Image Availability
        run: sleep 10

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_NAME \
            --image-uri $IMAGE_URI:$IMAGE_TAG